projectName: recipe
appName: recipe-frontend
publicUrl: myrecipeconnection.com

replicaCount: 1

containerRegistry: registry.digitalocean.com/chris-container-registry
imageLabel: frontend-latest

servicePort: 80
containerPort: 8000

googleClientSecret: hidden
googleClientId: hidden